import type { SimulationPreset, BlackHoleParams } from '../types/simulator';

export const DEFAULT_BLACK_HOLE_PARAMS: BlackHoleParams = {
  mass: 1.0,
  spin: 0.9,
  mode: 'kerr',
  diskEnabled: true,
  diskInnerRadius: 1.0,  // 1.0x r_isco
  diskOuterRadius: 16.0, // 16 M
  diskThickness: 0.15,
  diskDensity: 1.5,
  diskTemperature: 12000, // 12,000 K
  diskLuminosity: 2.0,
  diskRotationSpeed: 1.0,
  starDensity: 1.2,
  starBrightness: 1.5,
  backgroundBrightness: 1.0,
  dopplerBeaming: true,
  gravitationalRedshift: true,
  frameDragging: true,
  cameraDistance: 18.0,
  cameraInclination: 75.0, // 75 degrees inclination
  cameraAzimuth: 45.0,
  cameraFov: 50.0,
  autoOrbit: false,
  autoOrbitSpeed: 1.0,
  quality: 'high',
  maxRaySteps: 256,
  stepSize: 1.0,
  dynamicResolution: true,
  bloomEnabled: true,
  bloomStrength: 1.2,
  bloomRadius: 0.8,
  exposure: 1.2,
  gamma: 2.2,
  showSpacetimeGrid: false,
  showCriticalRadii: true,
  showVectorPaths: false,
  showDopplerHeatmap: false,
  showTelemetry: true,
};

export const SIMULATION_PRESETS: SimulationPreset[] = [
  {
    id: 'kerr-rotating',
    name: 'Rapidly Rotating Kerr',
    subtitle: 'a = 0.998 M',
    description: 'High spin rotating black hole exhibiting extreme frame dragging, asymmetric photon ring, and Doppler beaming.',
    params: {
      mass: 1.0,
      spin: 0.998,
      mode: 'kerr',
      cameraInclination: 75.0,
      cameraDistance: 16.0,
      dopplerBeaming: true,
      frameDragging: true,
    },
  },
  {
    id: 'schwarzschild',
    name: 'Schwarzschild Black Hole',
    subtitle: 'a = 0 (Non-rotating)',
    description: 'Spherically symmetric non-rotating black hole with ISCO at 6M and symmetric photon ring at 3M.',
    params: {
      mass: 1.0,
      spin: 0.0,
      mode: 'schwarzschild',
      cameraInclination: 70.0,
      cameraDistance: 18.0,
      dopplerBeaming: true,
      frameDragging: false,
    },
  },
  {
    id: 'sagittarius-a',
    name: 'Sagittarius A*',
    subtitle: '4.15 Million M☉ (Milky Way)',
    description: 'Supermassive black hole at the center of the Milky Way galaxy, observed by the Event Horizon Telescope.',
    params: {
      mass: 1.0,
      spin: 0.90,
      mode: 'kerr',
      diskTemperature: 9500,
      diskDensity: 1.2,
      diskLuminosity: 1.8,
      starDensity: 2.0,
      backgroundBrightness: 1.5,
      cameraInclination: 60.0,
      cameraDistance: 20.0,
    },
  },
  {
    id: 'm87-star',
    name: 'M87* Supermassive',
    subtitle: '6.5 Billion M☉ (Messier 87)',
    description: 'Giant supermassive black hole with iconic shadow and bright photon ring captured by EHT in 2019.',
    params: {
      mass: 1.0,
      spin: 0.94,
      mode: 'kerr',
      diskTemperature: 15000,
      diskDensity: 2.0,
      diskLuminosity: 2.5,
      bloomStrength: 1.5,
      cameraInclination: 72.0,
      cameraDistance: 22.0,
    },
  },
  {
    id: 'extreme-spin',
    name: 'Extreme Spin Near-Naked',
    subtitle: 'a = 0.999 M',
    description: 'Near-maximal Kerr spin parameter pushing general relativity metric limit toward r_isco ≈ 1.0M.',
    params: {
      mass: 1.0,
      spin: 0.999,
      mode: 'kerr',
      diskInnerRadius: 1.0,
      cameraInclination: 82.0,
      cameraDistance: 14.0,
      dopplerBeaming: true,
      frameDragging: true,
    },
  },
  {
    id: 'face-on',
    name: 'Face-On Polar View',
    subtitle: 'Inclination θ = 5°',
    description: 'Polar camera view looking directly down onto the rotating accretion disk, revealing symmetric Einstein rings.',
    params: {
      cameraInclination: 5.0,
      cameraDistance: 18.0,
      autoOrbit: false,
    },
  },
  {
    id: 'edge-on',
    name: 'Edge-On Equatorial View',
    subtitle: 'Inclination θ = 85°',
    description: 'Equatorial view showing dramatic relativistic Doppler boosting: approaching gas is blue-shifted, receding gas is dimmed.',
    params: {
      cameraInclination: 85.0,
      cameraDistance: 16.0,
      dopplerBeaming: true,
    },
  },
  {
    id: 'strong-lensing',
    name: 'Strong Lensing Einstein Ring',
    subtitle: 'Gravitational Light Deflection',
    description: 'Background star field distorted into continuous circular Einstein rings and duplicated stellar images.',
    params: {
      diskEnabled: false,
      starDensity: 2.5,
      starBrightness: 2.5,
      backgroundBrightness: 1.8,
      cameraDistance: 14.0,
      cameraInclination: 45.0,
    },
  },
  {
    id: 'photon-ring-closeup',
    name: 'Photon Ring Close-Up',
    subtitle: 'Sub-ring Light Trajectories',
    description: 'High magnification zoom on the sharp photon ring created by photons looping multiple times around the photon sphere.',
    params: {
      cameraDistance: 7.5,
      cameraFov: 35.0,
      quality: 'ultra',
      maxRaySteps: 384,
      bloomStrength: 1.4,
    },
  },
  {
    id: 'cinematic-orbit',
    name: 'Cinematic Orbit Mode',
    subtitle: 'Continuous Spacetime Flyby',
    description: 'Fluid auto-orbit camera motion sweeping around the Kerr black hole accretion disk.',
    params: {
      autoOrbit: true,
      autoOrbitSpeed: 1.5,
      cameraDistance: 20.0,
      cameraInclination: 70.0,
    },
  },
];
